# Generated by Django 4.2.7 on 2025-10-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_section_remove_question_form_delete_approvalrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('next_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_options', to='feedback_app.section')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_links', to='feedback_app.question')),
            ],
        ),
    ]
