# Generated by Django 5.1.2 on 2025-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_questionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('radio', 'Single Choice'), ('dropdown', 'Dropdown'), ('checkbox', 'Multiple Choice'), ('rating', 'Rating (1-5)'), ('rating_10', 'Rating (1-10)'), ('yes_no', 'Yes/No'), ('email', 'Email'), ('phone', 'Phone Number')], max_length=20),
        ),
    ]
