# Generated by Django 5.1.2 on 2025-10-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='next_section',
        ),
        migrations.AddField(
            model_name='section',
            name='next_section_on_submit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sections', to='feedback_app.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
