# Generated by Django 5.1.2 on 2025-10-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_remove_section_next_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enable_option_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('radio', 'Single Choice'), ('dropdown', 'Single Choice (Dropdown)'), ('checkbox', 'Multiple Choice'), ('email', 'Email'), ('phone', 'Phone Number'), ('rating', 'Rating'), ('yes_no', 'Yes or No')], max_length=20),
        ),
    ]
