# Generated by Django 4.2.7 on 2025-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_question_enable_option_navigation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='question',
            name='frontend_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='frontend_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
